### ISSUE TITLE
[Naming]: Improve function naming

### ISSUE THREAD

**Issue by ApolloX939** [pl608/mt_teams#2]
From my forked branch:

[init.lua#37-49](https://github.com/Beanzilla/mt_teams/blob/mine/init.lua#L37-L49)

```lua
function mt_teams.get_team_id(player)
    local meta = player:get_meta()
    return meta:get_int("mt_teams:team")
end

function mt_teams.get_team_name(player)
    local team_id = mt_teams.get_team_id(player)
    return mt_teams.get_team_name_by_id(team_id)
end

function mt_teams.get_team_name_by_id(id)
    return mt_teams.teams[id].name
end
```

I changed it so each of these functions are named better and I also show a much better approach on getting team name from the player.

To explain in further details, as a list:

- Changed `mt_teams.get_team` to `mt_teams.get_team_id`
- Changed `mt_teams:team` to use a int instead of float as floating points can vary and thus the classical 3.0 != 3.0 as you may get 3.0000001 or 2.999999 in example.
- Changed `mt_teams.get_team_name` to use obtainable team id to lookup the team name (thus removing the meta `mt_teams:name` from the player), why? .... Because if you wanted to support renaming the team you'd have to do goofy code to update the meta value for every player on that team.
- Changed `mt_teams.get_name_id` to `mt_teams.get_team_name_by_id`, this extra "by_id" allows us to separate `get_team_name` as it takes a player, while the `get_team_name_by_id` takes it by id.
- Changed `mt_teams.remove_player` where we change table contents within a loop (this is more of a issue if you were changing more than 1 value within that loop, the loop is changing size while we are iterating over it!)
- Changed `mt_teams.remove_player` how we loop over the table (we're not in python anymore, [pairs or ipairs](https://stackoverflow.com/questions/55108794/what-is-the-difference-between-pairs-and-ipairs-in-lua#55109411))

> I might look like I just want to nit pick, but it's to help you write better code, and to help you develop a cool mod.

**Comment by pl608** [comment]
Thanks for the upgrade in naming! Did you change all of the `get_float`s to `get_int`s? There were a more such as when you set the team and that might cause some issues. Also somewhere when I was programming this, intelisense did not show `get_int` as an option for the MetaRef object which is one of the reasons I did not use it.
Also...
> Changed mt_teams:team to use a int instead of float as floating points can vary ... as you may get 3.0000001 or 2.999999 in example.

when `mt_teams:team` is set (at least at the first join) it uses `math.ceil()` to prevent issues like that
